Migrate earnings and spendings to transactions table
RocketC31/budget pull request #80
Opened 2022-11-19 11:45 UTC by RocketC31

2022-11-19 11:54 UTC, RocketC31 commented
Hi @sebastiaanspeck i have worked on this issue.

I have change many many files.
Initialy, we have say to use tinyint for type column on transaction table. 

But, when i have start to do it. I noticied, on all other table, it's simple string... For not make this table the onlyone who have a tinyint for distinguish earning/spending. I have make exactly the same thing. Just add a string column. Not an enum.

I don't know if it's the best solution to make "like other table"... What's your opinion for that ?

Appart from that i have see, spendings and earning are used for activites / attachments. So i have make a migration with this consideration.

Same thing if you can review a little when you will have time, it will be more secure ! Thanks

2022-11-20 16:35 UTC, sebastiaanspeck requested changes

2022-11-20 16:35 UTC, sebastiaanspeck commented on database/migrations/2022_11_19_041148_create_transactions_table.php
> +        $sql = "INSERT INTO transactions
Why use raw SQL statements instead of using `DB::`-ways? In my opinion that looks more clean to me.

2022-11-20 16:44 UTC, RocketC31 commented on database/migrations/2022_11_19_041148_create_transactions_table.php
> +        $sql = "INSERT INTO transactions
I have write on `$sql` variable for better lisibility but i use just after `DB::statement($sql);` for run it. I have read it here 
https://laravel.com/docs/9.x/database#running-a-general-statement because my sql no need to have a return value.

I don't know if it's the best way for run simple sql. What method would you have used?

2022-11-21 13:16 UTC, sebastiaanspeck commented on database/migrations/2022_11_19_041148_create_transactions_table.php
> +        $sql = "INSERT INTO transactions
When looking at it again, it seems fine. I thought of a construction like:
```
foreach (DB::table('spendings') as $spending) {
             Transaction::create(<properties from $spending>);
}
```

But I want to find out if using this way or your way, affects the balance etc.

2022-11-21 13:16 UTC, sebastiaanspeck approved these changes
Overall these changes seem okay to me.

2022-11-21 13:27 UTC, sebastiaanspeck commented
This pull request is ready to merge. I've tested it using existing data.

2022-11-21 14:29 UTC, RocketC31 commented
Thanks @sebastiaanspeck i have test too for apply and rollback with data. Thanks for your review !

2022-11-21 14:29 UTC, merged